version: '3.8'

services:

  # ETL Data Storage
  postgres:
    image: postgres:12-alpine
    volumes:
      - "./databases/postgres/data:/var/lib/postgresql/data"
      - "./databases/postgres/init/1_create_table.sql:/docker-entrypoint-initdb.d/1_create_table.sql"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: castiron # Not Secure
      POSTGRES_USER: castiron
